### ISSUE TITLE
Output not being compiled-down

### ISSUE THREAD

**Issue by samdenty** [palmerhq/tsdx#101]
### Current Behavior

Currently the output is not being transpiled so it can be supported on older browsers eg. `class {}`.

### Suggested solution(s)

Use `@babel/preset-env` and default to ES2015 output

### Additional context

It's problematic because some setups don't transpile node_modules. This prevents extending classes from `tsdx` as babel doesn't like es5->es6 interop.

**Comment by sw-yx** [comment]
i think @jaredpalmer has strong feelings about this one. i think it may be a gold idea to try to ship modern js in libraries and force downstream toolkits to change. any idea why CRA doesnt do the transpile?

**Comment by samdenty** [comment]
@sw-yx I agree on shipping modern code, unfortunately some tools (parcel for one)/custom webpack setups aren't configured out the box to transpile node_modules.

How about keeping `preset-env`, but adding a `browserlist` to `package.json` that targets the evergreen by default?

**Comment by sw-yx** [comment]
🤷🏼‍♂️this is jared's call.

**Comment by jaredpalmer** [comment]
Oof. 😐

**Comment by alanrsoares** [comment]
I'm also having issues with spread operator not being transpiled

**Comment by jaredpalmer** [comment]
Will investigate in the mornjng

**Comment by jaredpalmer** [comment]
I think this must have to do with cjs settings.

**Comment by jaredpalmer** [comment]
Can someone explore this?

**Comment by hedgerh** [comment]
I can take a look, but need to gather a little context.  Looks like there's a PR to add `preset-env`? https://github.com/palmerhq/tsdx/pull/102

should the output be compiling down, but something's up with the cjs settings?

**Comment by jaredpalmer** [comment]
Honestly I haven’t diagnosed the root issue. What I know right now is that Formik’s old Rollup config was fine (on master), but the tsdx is not for cjs

**Comment by hedgerh** [comment]
Np. I can hunt for the root issue.  I just wanted to confirm what the expected behavior is.

**Comment by hedgerh** [comment]
Figured it out.  There was a `tsconfigOverride` declared in the typescript rollup plugin that forced `target` to `esnext`.  Changed it to default to `es5` and it can be declared in a tsconfig at the project level.  https://github.com/palmerhq/tsdx/pull/111
