### ISSUE TITLE
New project includes yarn-error.log

### ISSUE THREAD

**Issue by ztolley** [palmerhq/tsdx#105]
Steps to recreact
run: npx tsdx create mylib
cd mylib
cat yarn-error.log

See that jared is running 11.8.0 and had a syntax error in /Users/jared/workspace/github/jaredpalmer/tsdx/templates/react/package.json

**Comment by rozenmd** [comment]
Just taking a look at this @sw-yx & @jaredpalmer.

Seems like the `yarn-error.log` was inadvertently packaged up and sent to npm - can't make it show up running a cloned copy of tsdx locally

**Comment by jaredpalmer** [comment]
Whoops 😬

--
Jared
________________________________

**Comment by huchenme** [comment]
Is it ok for me to take up this issue and get familiar with this library? This repository is so good that I would love to spend time learning from it and hopefully contribute!

**Comment by huchenme** [comment]
Actually, I am not to reproduce this issue by repeating the steps

**Comment by jaredpalmer** [comment]
Fixed in the latest release

**Comment by huchenme** [comment]
@jaredpalmer do you think [this PR](https://github.com/palmerhq/tsdx/pull/115) is valuable? if not I could close it
