### ISSUE TITLE
Adding to an existing library 

### ISSUE THREAD

**Issue by andyboythekid** [palmerhq/tsdx#106]
I was curious about adding this to an existing library. I noticed that the library generates a few files and some config in package.json. My solution was to just copy paste these changes into my library, but was wondering if there was an easier solution (for when I use this again in the future). 

Cheers!

**Comment by sw-yx** [comment]
not right now, and tbh im not sure this should exist. dont want to encourage turning off all thinking. but yea most existing codebases should be able to switch over to tsdx easily. let us know what pain points you ran into specifically

**Comment by hedgerh** [comment]
@andyboythekid is the library you added tsdx to on github?  would be interested to see it.  im not sure how easy it'd be to automate adding `tsdx` to an existing library.  it may not be so bad, but possible issues:  differing ts configs, differing rollup/babel plugins, differing folder structures.  it'd also have to overwrite your current npm scripts.  it could be really cool if someone could just quickly setup tsdx in a project where their build system/dev environment is outdated.

i wonder if it's easier to just create a fresh `tsdx` project and copy stuff over?

**Comment by andyboythekid** [comment]
that’s what i ended up doing, just a fresh project and copied everything over, seemed simple enough. here’s the project i added it to: https://github.com/andyboythekid/react-native-navigation-library

**Comment by sw-yx** [comment]
alright i'mma close this one. someday a guide may be warranted. but ideally i'd like everyone using tsdx to be comfortable figuring this one out if they need it since the scope of migrations is very large.
