### ISSUE TITLE
[feature?] run `yarn init` right after to initialize package.json details. possibly git init too.

### ISSUE THREAD

**Issue by sw-yx** [palmerhq/tsdx#112]
### Current Behavior

right now the immediate output of tsdx is not publishable. in particular, git isn't initiated, which we could do, and also there isn't a repository defined in package.json. No license, no description.

### Desired Behavior

high quality package.json resulting from tsdx scaffolded libraries.

### Suggested Solution

running `yarn init` or `npm init` would walk the user through the usual CLI guide including filling out a description and picking a license as well as supplying the default author email (even tho mine is a fake email :)). all are pretty nice things to have.

### Who does this impact? Who is this for?

all users

### Describe alternatives you've considered

do nothing

---

i can implement if we agree this is something we want

**Comment by jaredpalmer** [comment]
I would prefer we do not add any more prompts to the init command. We want to keep that frictionless. I don’t think we should initialize git either. As for publishing, I’d rather build out a publish command that wraps or forks np that would ensure the package is publishable and handle any missing details

--
Jared

________________________________

**Comment by sw-yx** [comment]
ok

**Comment by karlhorky** [comment]
FWIW was just thinking this same thing, was going to submit an issue :)

Just leaving this here on the closed issue then!
