### ISSUE TITLE
Remove UMD format from default build outputs

### ISSUE THREAD

**Issue by jaredpalmer** [palmerhq/tsdx#120]
It's really really slow to build for UMD and very very few modules really need to have a standalone `<script>` tag-ready output. 

Thoughts @sw-yx ?

**Comment by TrySound** [comment]
I use umd dev/prod bundles to track library size with bundled dependencies for development and production.

**Comment by enesTufekci** [comment]
@jaredpalmer I was going to ask the same thing. Hey @TrySound you can still use `--format umd`. I am creating a pr for this.

**Comment by sw-yx** [comment]
i agree it should be a flag not a default. we’re gonna need a tsdxrc soon...

**Comment by jaredpalmer** [comment]
Not yet.

**Comment by aleclarson** [comment]
Maybe `tsdx create` should have a `--umd` flag that adds the `umd` entry to `package.json`. Then `tsdx build` can just check `package.json` to know when to build the UMD bundle.
