### ISSUE TITLE
Add ability to specify custom tsconfig.json

### ISSUE THREAD

**Issue by jaredpalmer** [palmerhq/tsdx#121]
### Current Behavior

TSDX merges `./tsconfig.json` and its internal overrides.

### Desired Behavior

```bash
tsdx build --flag=./tsconfig.foo.json
```

### Suggested Solution

Add the flag to `build`, `watch` (and `test`?) commands

### Who does this impact? Who is this for?

err'body in da club. More specifically I need this in Formik. The reason is the Formik has multiple tsconfig's to support vscode, tsdx, and storybook. **This would also allow us to self-compile tsdx with tsdx which is trippy.** 

### Additional context

The typescript cli (`tsc`) uses the `--project` flag (and `-p` alias) for this behavior. See screenshot. This is not a very intuitive flag name. However, I think it probably makes sense to parallel the API? An alternative would just be `--config` or `--tsconfig`. I think `--tsconfig` is the most explicit and it lets us use `--config` for `tsdx` config one day. 

<img width="1095" alt="Screenshot 2019-05-30 08 11 12" src="https://user-images.githubusercontent.com/4060187/58632045-8180c400-82b2-11e9-800b-cb6d77be2d32.png">

**Comment by sw-yx** [comment]
https://github.com/palmerhq/tsdx/pull/124
