### ISSUE TITLE
[idea] use production profiling build in react example playground

### ISSUE THREAD

**Issue by sw-yx** [palmerhq/tsdx#137]
### Current Behavior

it can  be helpful to use the new devtools profiler in production (https://fb.me/react-profiling). it has different characteristics than in dev. we dont enable this by default but we might as well for the playground where perf isnt as impt as debugging.

### Desired Behavior

profiler build by default

### Suggested Solution

set these parcel aliases:

```js
  "alias": {
    "react": "../node_modules/react",
    "react-dom": "../node_modules/react-dom/profiling",
    "scheduler/tracing": "../node_modules/scheduler/tracing-profiling"
  },
```

### Who does this impact? Who is this for?

react users

### Describe alternatives you've considered

do nothing

**Comment by jaredpalmer** [comment]
go for it

**Comment by sw-yx** [comment]
i accidentally did this as a direct commit  (!!) rather than a PR, which is totally my bad. i think in this single case its fine but we might wanna turn off direct commits to master. anyway case closed.
