### ISSUE TITLE
Production bundle for ES format is not enough for a development

### ISSUE THREAD

**Issue by FredyC** [palmerhq/tsdx#140]
### Current Behavior

Webpack will use ES format but being in a development mode it means the wrong assumption from 3rd modules like `invariant` which then throws an error.

![image](https://user-images.githubusercontent.com/1096340/59373506-1cb17900-8d4a-11e9-807c-79cb18e8401d.png)

https://github.com/zertosh/invariant/blob/fae1c859f3eec25025dc6019bf7f7fdb78a27307/invariant.js#L26

### Expected behavior

Same behavior as for CJS should be used and provide development bundle along with `index.es.js`.

### Suggested solution(s)

Should be pretty straightforward to add a line in here...

https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/index.ts#L98

And utilize logic for creating index file...

https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/index.ts#L277

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.6.1
| TypeScript       | 3.5.1
| Browser          | N/A
| Yarn         | 1.16.0
| Operating System | Windows x64

**Comment by TrySound** [comment]
I agree. ESM bundle should have NODE_ENV untouched.

**Comment by jaredpalmer** [comment]
Can you send a PR? I am out of office today. Should be straight forward

**Comment by FredyC** [comment]
Working on it :)
