### ISSUE TITLE
@scope/package-name results in ugly build file names

### ISSUE THREAD

**Issue by sisp** [palmerhq/tsdx#144]
### Current Behavior

A package name that contains an NPM scope results in ugly build file names, e.g. `@myscope/mypackage` results in `myscopemypackage.{cjs,es,umd}.{development,production}.js[.map]`.

### Expected behavior

I would prefer to either add a dash between the scope and the package name, i.e. `myscope-mypackage.{cjs,es,umd}.{development,production}.js[.map]`, or to omit the scope entirely, i.e. `mypackage.{cjs,es,umd}.{development,production}.js[.map]`.

Opinions?

**Comment by sw-yx** [comment]
really dont care but pr welcome to tweak the safeName function
