### ISSUE TITLE
ESM module is not minified in v0.7.2

### ISSUE THREAD

**Issue by dance2die** [palmerhq/tsdx#155]
### Current Behavior

Only one ESM module ("*.esm.js") is generated instead of "*.esm.production.js" or "*.esm.development.js"

![current behavior](https://user-images.githubusercontent.com/8465237/59888261-dfc23380-9394-11e9-99e4-903cca0a49a3.png)

I've also tried to pass the `--format cjs,esm,udm` but only one ESM file is generated.

![one esm](https://user-images.githubusercontent.com/8465237/59888322-21eb7500-9395-11e9-9f9b-3e34a3d9abb1.png)

### Expected behavior

Two ESM files (production & development) should be generated.

### Suggested solution(s)

Generate prod/dev files where "dev" is minified.

### Additional context

Previous version (0.6.1) used to generate prod/dev versions.

- Unpkg of my library - https://unpkg.com/react-use-localstorage@3.1.2-alpha.1/dist/
- package.json file with tsdx v0.6.1 - https://unpkg.com/react-use-localstorage@3.1.2-alpha.1/package.json

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.7.2
| TypeScript       | 3.5.2
| Browser          | N/A
| npm/Yarn         | yarn version 1.16.0
| Operating System | Windows 10 build 1903

**Comment by TrySound** [comment]
Hi, this worked wrong. Two bundles required commonjs wrapper which breaks the point of using es modules and breaks all optimisations. All bundlers are able to replace NODE_ENV with production or development. This is a kind of standard for react modules. With webpack it's only one option `mode`.

**Comment by sw-yx** [comment]
basically i think this is working as designed. if you're using the ESM build, you're gonna want to do the minification higher up the chain. lmk if that sounds wrong @TrySound

**Comment by dance2die** [comment]
Thank you. @TrySound & @sw-yx
I have questions in-line below.
_Sorry about the ignorance and I'd like to learn what I don't know._ 🙇‍♂️

@TrySound

> Two bundles required commonjs wrapper which breaks the point of using es modules and breaks all optimisations.

Would having prod/dev ESM outputs break optimizations so one ESM file is generated?

> All bundlers are able to replace NODE_ENV with production or development. 

I tried the build with "NODE_ENV" to "production" for `tsdx build` and the ESM is not minified.

> This is a kind of standard for react modules. With webpack it's only one option mode.

I am not sure where Webpack fits 😅

@sw-yx
> if you're using the ESM build, you're gonna want to do the minification higher up the chain.

Would it require using Webpack to minify tsdx-generated ESM module?

**Comment by TrySound** [comment]
@dance2die You may use any bundler. All of them supports NODE_ENV replacement and minification.

There is not way to deliver two production and development bundles to user without requirement to manually alias paths. So we provide a single bundle which user bundler should process.

**Comment by dance2die** [comment]
> this worked wrong

Ah. I kind of see what you mean.
Would my understanding be correct that,

1. v0.6.1 generated prod/dev versions for both ESM  & CJS bundles, it required users to set which path to be the main package to use using an alias path (would it be [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias) in case of Webpack?)

2. CJS is in prod/dev bundles as to follow React module practice
and ESM is now a single file, which tsdx users should manually minify "higher up the chain".

Lastly, would "node module resolution" be what I should be research/learning to better understand this convo?

**Comment by dance2die** [comment]
I will close the issue as this is working as designed.

**Comment by jaredpalmer** [comment]
Tbh I copied the esm setup from microbundle which I think builds minified esm. Maybe so you can use `<script type=module>` or something idk? Anyways. It is working as expected. It’s up to your app to optimize it

**Comment by dance2die** [comment]
Thank you, Jared.
Will do more research 🙂
