### ISSUE TITLE
Any guide about creating demo pages for created libraries

### ISSUE THREAD

**Issue by pie6k** [palmerhq/tsdx#156]
eg. I'm creating react hook package and I'd like to create a simple demo page that is presenting it.

Could you provide some 'good way' of doing it?

**Comment by sw-yx** [comment]
you can use the example playground we set up for you: https://github.com/palmerhq/tsdx/tree/master/templates/react/example

**Comment by jaredpalmer** [comment]
Probs worth adding a paragraph to the docs about deploying to netlify or Gh pages

**Comment by luisrudge** [comment]
don't we need a playground for libs that are not react based? Like.. if you're creating a browser library, you'd expect to have somewhere to test that library, right? 🤔
