### ISSUE TITLE
CLI version is missing

### ISSUE THREAD

**Issue by sw-yx** [palmerhq/tsdx#29]
### Current Behavior

`npx tsdx -v` returns `tsdx, 0.0.0`

### Expected behavior

proper version

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.3.0
| TypeScript       | 3.x
| Browser          | chrome

```

    OS: macOS High Sierra 10.13.4
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
```

**Comment by aleclarson** [comment]
Fixed in 3f8d25e96a6c83f5cadcbd987d8dcdc58c68628d
