### ISSUE TITLE
`create` command with React (and other template) prompt

### ISSUE THREAD

**Issue by sw-yx** [palmerhq/tsdx#33]
Yeah that could work. I kinda prefer a prompt here cuz I can never remember the flags

_Originally posted by @jaredpalmer in https://github.com/jaredpalmer/tsdx/issues/5#issuecomment-459538795_

**Comment by jaredpalmer** [comment]
Agreezy. How should this work? This is much harder than it used to be because of the new "multiple versions of react" error message with hooks

**Comment by sw-yx** [comment]
i've run into that, but have no problems with my set up (see the `example` folder in https://github.com/sw-yx/react-netlify-identity-widget). stole that from @transitive-bullshit and it works fine. hehe ironically since we last talked i've gained a lot more cli experience due to netlify so i am actually in a position to contribute this right now. (see https://gist.github.com/sw-yx/6f97b9d7f3efbfad4c8e5b8a14b5bd27/)

so as for "how should this work" i think we literally go for a prompt, and let people pick templates, and scaffold it out to an `example` subfolder with the linking done for you. exactly like create-react-library.
