### ISSUE TITLE
compress option in `terser` inside production es rollup config produces invalid JS 

### ISSUE THREAD

**Issue by sw-yx** [palmerhq/tsdx#36]
### Current Behavior

here is my repo i'm working on https://github.com/sw-yx/react-netlify-identity-widget/tree/rollupProductionIssue

if you:

```bash
yarn build
yarn link
cd example
yarn && yarn link "react-netlify-identity"
yarn start
```

you will see this error:

![image](https://user-images.githubusercontent.com/6764957/56846233-e6539380-689a-11e9-8f2d-07f02ada767b.png)

however if you change the package.json to use the development versions:

![image](https://user-images.githubusercontent.com/6764957/56846237-f8cdcd00-689a-11e9-8e83-ce7a7d9cb2c3.png)

it works!!

to me this indicates a rollup config issue.

### Expected behavior

the production output should work the same as development output

### Suggested solution(s)

i think this could be a terser bug. or a setting that is incompatible with React.

here is the offending unexpected token - prettified for easier reading

![image](https://user-images.githubusercontent.com/6764957/56846272-77c30580-689b-11e9-9680-30e080eeb4bc.png)

i'm not sure what rollup setting caused this but it definitely only exists in the production build.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |	0.3.4
| TypeScript       | 3.4.4
| Browser          | chrome
| npm/Yarn         |yarn
| Operating System | osx

**Comment by sw-yx** [comment]
what's the size impact on you if you turn off compress? i dont have the option because my code plain doesnt work without it (and its not like i'm doing some crazy nonidiomatic React stuff). as far as i can see, thats the only option for now, and i pray @TrySound can figure it out. 

We can also choose to document it as well as how to patch the package, for early adopters of TSDX who may run into this.

**Comment by TrySound** [comment]
To be honest terser code is unreadable. I can't find a fix for that. You may turn off collapse_vars option. It should fix the problem.

**Comment by sw-yx** [comment]
ohh i see. i thought there was no option available. thank you i will try that.

**Comment by jaredpalmer** [comment]
So what should we do for now?

**Comment by sw-yx** [comment]
@jaredpalmer  i have verified that Bogdan's solution works. i recommend adopting it in tsdx and have PR'ed accordingly
