### ISSUE TITLE
code splitting support

### ISSUE THREAD

**Issue by sw-yx** [palmerhq/tsdx#42]
### Current Behavior

currently we bundle single files, named per environment/module format.

to support code splitting (which is the default behavior of Rollup v1 which we [just upgraded to](https://github.com/palmerhq/tsdx/issues/37)) we'll have to evolve this to a folder format with multiple files. 

right now this https://github.com/sw-yx/react-netlify-identity-widget/blob/master/src/index.tsx#L8 doesnt produce a separate bundle for me :(

### Desired Behavior

code splitting support.

### Suggested Solution

as above

### Who does this impact? Who is this for?

all users, partiuclarly React users, who want to offer code splitting as a feature

### Describe alternatives you've considered

no change

### Additional context

i'm unsure what existing priorities this may conflict with for you.

**Comment by sw-yx** [comment]
important caveat - Rollup does not have code splitting support for UMD and IIFE builds, which somewhat complicates things. so we need one config for code splitting, and another for noncodesplitting.

**Comment by sw-yx** [comment]
further investigation: using code splitting means we have random named chunks, and i get `Error: output file in rollup options should be specified` error with 
@TrySound's `rollup_plugin_size_snapshot`. i've disabled it for now as i dont reallycare about the snapshot based on this (https://github.com/TrySound/rollup-plugin-size-snapshot/issues/23) it seems it just wasnt designed with code splitting in mind.

**Comment by jaredpalmer** [comment]
I need to read more about Rollup code splitting as I don’t understand how it would be beneficial for a library

**Comment by TrySound** [comment]
I will fix size snapshot when I will have a time.

**Comment by jaredpalmer** [comment]
I just skimmed the docs. @sw-yx Can you elaborate more on the use case? I don't really understand why you want to code split identity widget itself in the first place. Instead, it makes more sense to just show consumers how to code split the the entire login route / modal?

**Comment by sw-yx** [comment]
yeah. i withdraw my stupid idea. :) thanks for humoring me

**Comment by agilgur5** [comment]
Code-splitting is currently supported by #367
