### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by damianesteban** [palmerhq/tsdx#60]
### Current Behavior

When I run `tsdx create mylib` I receive the following error:

```Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/tsdx/templates/basic'```

### Expected behavior

I'm not sure,I haven't gotten it to work yet 😄 

### Suggested solution(s)

N/A

### Additional context

I have seen other similar errors reported and they were marked as closed. Not sure why I'm having this issue.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |  0.5.3
| TypeScript       | 3.4.5
| Browser          | Google Chrome
| npm/Yarn         | 6.9.0
| Operating System |10.14.4

**Comment by jaredpalmer** [comment]
Bump to 0.5.4

**Comment by jaredpalmer** [comment]
Had a botched release where i forgot to change the `files`

**Comment by damianesteban** [comment]
Great, thank you.
