### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by z0al** [palmerhq/tsdx#67]
I have an existing project that uses microbundle and I wanted to give this project a shot.

### Current Behavior

When I run `tsdx build` I get this error, but the outputted `dist` folder seems fine.

```sh
❯ npx tsdx build
✓ Creating entry file 2.1 secs
(node:7935) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at then.then (/home/z0al/x/github/stash/packages/core/node_modules/rollup-plugin-size-snapshot/dist/treeshakeWithRollup.js:67:36)
(node:7935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### Expected behavior

No errors

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.5.4
| TypeScript       | 3.4.5
| Browser          | N/A
| npm/Yarn         | npm
| Operating System | Debian/Linux

**Comment by James-Quigley** [comment]
Is that proj open source by chance?

**Comment by z0al** [comment]
Oh, yeah. My bad. I tried to add `tsdx` to [this package](https://github.com/z0al/stash/tree/master/packages/stash-it).

My steps:

1. Install: `npm add -D tsdx`
2. clean: `rm -rf dist`
3. build: `npx tsdx build`

**Comment by James-Quigley** [comment]
![image](https://user-images.githubusercontent.com/12548978/57032050-5bb2c180-6c17-11e9-88ee-2004ffa32b55.png)
Interestingly enough, worked totally fine for me. What version of Node and npm are you using?

**Comment by z0al** [comment]
That's weird!

```
$ node --version
v10.15.1

$ npm --version
6.4.1
```

**Comment by jaredpalmer** [comment]
We should figure out which versions of node we support

**Comment by z0al** [comment]
I tried node v12 and it works now. Both node v10 and v11 don't work :/

**Comment by James-Quigley** [comment]
I'm on Node v10 and it worked just fine

**Comment by z0al** [comment]
@James-Quigley do you add `tsdx` to dependencies first before running the build?

After more testing, I can say that the `npx tsdx build` works only (at least on my machine) if I didn't add `tsdx` as a dep, here:

**Fails:**

```sh
$ rm -rf node_modules && npm i
$ npm add tsdx     // same behavior with -D flag
$ npx tsdx build
// fails same error as the original post
```

**Works:**

```sh
$ npm remove tsdx
$ rm -rf node_modules && npm i
$ npx tsdx build
✓ Creating entry file 2 secs
✓ Building modules 1.7 secs

```

Tested with Node v10, v11, and v12 ¯\\\_(ツ)_/¯

**Comment by James-Quigley** [comment]
@z0al It seems that what matters is the order in which I do my npm actions. If I add tsdx first, then npm install then build, its a pass. If I install, then add tsdx, it fails.
```
*Pass:*
```
$ git reset --hard
$ git clean -xdfff
$ npm add tsdx
$ npm i
$ npx tsdx build // PASS
```

*Fail:*
```
$ git reset --hard
$ git clean -xdfff
$ npm i
$ npm add tsdx
$ npx tsdx build // FAIL
```

However tsdx version is 0.5.5 in both, and the only change is the package.json. Unsure of why one passes and the other doesn't

**Comment by jaredpalmer** [comment]
Try 0.5.6

**Comment by z0al** [comment]
@jaredpalmer  Same as [above](https://github.com/palmerhq/tsdx/issues/67#issuecomment-488717418) for me.

**Comment by jaredpalmer** [comment]
hrmmmm.

**Comment by jaredpalmer** [comment]
Can you try out `npx tsdx@next create lib` and see if it works

**Comment by z0al** [comment]
Yep, it works.

**Comment by z0al** [comment]
Doesn't occur anymore
