### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by jaredpalmer** [palmerhq/tsdx#7]

**Comment by diegohaz** [comment]
Why not eslint? Even TS is migrating to it: https://github.com/Microsoft/TypeScript/issues/30553

**Comment by jaredpalmer** [comment]
Yeah made issue before the announcement

**Comment by bbugh** [comment]
I just started using tsdx and found the lack of linting surprising! 

I've added linting with `@typescript-eslint` with `prettier` integrated, using `lint-staged` with husky for running on staged files, and it's worked out very well. 

Does that sound useful for a patch?

**Comment by sw-yx** [comment]
we have a tsdx lint command that is a bit stale - https://github.com/palmerhq/tsdx/pull/99 i havent been involved with the discussion tho and am not sure what @jaredpalmer's plan is here

**Comment by robphoenix** [comment]
In a *basic* tsdx project, to deal with 1. @bbugh mentioned

> Even if the "basic" template is selected, the react-app package is added to the .eslintrc.js file when the yarn lint --write-file command is run:

we have to directly call eslint rather than `tsdx lint`, in package.json:

```json
"lint": "eslint --fix \"./src/**/*.ts\""
```

Is there a way to override/ignore the tsdx eslint config? Or document this as a recommended option?
