### ISSUE TITLE
install tslib by default

### ISSUE THREAD

**Issue by aleclarson** [palmerhq/tsdx#72]
Libraries should be using `tslib` to eliminate duplicate code.

Also need `"importHelpers": true` in the `tsconfig.json`

**Comment by jaredpalmer** [comment]
Agreed

**Comment by aleclarson** [comment]
Hahaha! On it 😆

**Comment by sw-yx** [comment]
lol, power move right there

**Comment by aleclarson** [comment]
@sw-yx a power move, or me being nice? :P

**Comment by sw-yx** [comment]
both :)
