### ISSUE TITLE
Document how to use lodash/lodash-es optimization

### ISSUE THREAD

**Issue by jaredpalmer** [palmerhq/tsdx#8]

**Comment by BetterCallSky** [comment]
I would suggest avoiding using lodash in libraries. Especially in libraries that are small.
Lodash functions are huge. For example: `lodash.keyBy` has 14KB after minification, but it can be reimplemented in 4 lines.

Example https://github.com/react-dnd/react-dnd/issues/1202

**Comment by rafinskipg** [comment]
But is there any solution for this? for large projects that are migrating and still use lodash
