### ISSUE TITLE
No name was provided for external module

### ISSUE THREAD

**Issue by gevalo1** [palmerhq/tsdx#87]
### Current Behavior

My code isn't getting bundled because tsdx treats everything as external modules, the resulting bundle only contains the compiled `index.ts` file.

### Expected behavior

My files shouldn't be treated as external modules.

### Suggested solution(s)

Could it be something related to the `external` function? https://github.com/palmerhq/tsdx/blob/v0.5.7/src/utils.ts#L19

### Additional context

I'm getting the following warning for all my `.ts` files (except the root `index.ts` file):
```
No name was provided for external module 'C:/xyz/xyz/xyz/xyz.ts' in output.globals – guessing 'xyz_ts'
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.5.7
| TypeScript       | 3.4.5
| Browser          | Chrome Version 74.0.3729.131
| npm/Yarn         | Node v10.11.0, npm 6.4.1
| Operating System | Windows 10

**Comment by a-type** [comment]
Looks like a Windows problem, I'm experiencing it too.

My recommendation would be to use [path.isAbsolute](https://nodejs.org/api/path.html#path_path_isabsolute_path)

**Comment by a-type** [comment]
@jaredpalmer version `v0.5.8` published on NPM doesn't appear to include this change in the distributed code.
