### ISSUE TITLE
jest.config.js created with hardcoded paths

### ISSUE THREAD

**Issue by veksen** [palmerhq/tsdx#90]
### Current Behavior

When running `yarn test`, a `jest.config.js` is created, but the paths are hardcoded to the computer that runs it.

```
module.exports = {
    "transform": {
        ".(ts|tsx)": "/Users/veksen/Projects/mylib/node_modules/ts-jest/dist/index.js"
    },
    "transformIgnorePatterns": [
        "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleFileExtensions": [
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "node"
    ],
    "collectCoverageFrom": [
        "src/**/*.{ts,tsx}"
    ],
    "testMatch": [
        "<rootDir>/test/**/*.(spec|test).{ts,tsx}"
    ],
    "testURL": "http://localhost",
    "rootDir": "/Users/veksen/Projects/mylib",
    "watchPlugins": [
        "/Users/veksen/Projects/mylib/node_modules/jest-watch-typeahead/filename.js",
        "/Users/veksen/Projects/mylib/node_modules/jest-watch-typeahead/testname.js"
    ]
}
```

### Expected behavior

Probably either use `<rootDir>`, or should `jest.config.js` be gitignored? It doesn't seem to make sense to commit it in its current state (aka, the user computer hardcoded)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.5.7
| TypeScript       | 3.4.5
| Browser          | N/A
| npm/Yarn         | 6.4.1/1.15.2
| Operating System | MacOS

**Comment by jaredpalmer** [comment]
I think i just need to get rid of my `require.resolve`

**Comment by jaredpalmer** [comment]
Upgrade and remove, your should remove `jest.config.js`
